"""
SAM2 Point-Prompt Patch Extractor
===================================
Generates Option A patches using SAM2 point prompts.

For each CoralNet annotation point (image, row, col, species):
    1. Feed (row, col) as SAM2 foreground point prompt
    2. SAM2 generates a mask for that specific coral colony
    3. Extract bbox crop with background zeroed (Option A style)
    4. Save patch with species label

Speed: ~0.3s per annotation with caching -> ~8-10 hours for 240k annotations
Resumable: tracks progress in checkpoint file, safe to interrupt and restart

Usage from the repository root:
    conda activate coralnet10
    python src/patches/extract_sam2.py

Default local paths:
    outputs/split_manifest.csv          manifest from src/data/build_manifest.py
    models/sam2.1_hiera_base_plus.pt    SAM2 weights, externally downloaded
    external/sam2/                      optional local SAM2 repo clone
    outputs/patches_sam2/               generated patches

All defaults can be overridden with command-line arguments.
"""

import argparse
import sys, os
_script_dir = os.path.dirname(os.path.abspath(__file__))
if _script_dir in sys.path:
    sys.path.remove(_script_dir)
sys.path = [p for p in sys.path
            if not os.path.exists(os.path.join(p, "sam2", "build_sam.py"))]

import csv, json, logging, random, time
from collections import defaultdict
from pathlib import Path

import cv2
import numpy as np
import pandas as pd
import torch


# ── Project paths ─────────────────────────────────────────────────────────────

def find_project_root(script_path: Path) -> Path:
    """Return the repository root so the script works from any current folder."""
    for parent in [script_path.parent, *script_path.parents]:
        if (parent / "README.md").exists() or (parent / ".git").exists():
            return parent

    # Expected GitHub location: src/patches/<this_file>.py
    if script_path.parent.name == "patches" and script_path.parent.parent.name == "src":
        return script_path.parent.parent.parent

    return script_path.parent


PROJECT_ROOT = find_project_root(Path(__file__).resolve())
MODEL_DIR = PROJECT_ROOT / "models"
OUTPUT_ROOT = PROJECT_ROOT / "outputs"


def repo_path(*parts: str) -> Path:
    """Build an absolute path inside this repository."""
    return PROJECT_ROOT.joinpath(*parts)


def resolve_path(path_value) -> Path:
    """Resolve user paths. Relative paths are interpreted from the repo root."""
    path = Path(path_value).expanduser()
    if path.is_absolute():
        return path
    return repo_path(str(path)).resolve()

# ── Configuration ─────────────────────────────────────────────────────────────

SAM2_REPO    = repo_path("external", "sam2")
DATA_ROOT    = repo_path("data", "CoralNet_Data")
OUTPUT_DIR   = repo_path("outputs", "patches_sam2")
MANIFEST_CSV = repo_path("outputs", "split_manifest.csv")
CHECKPOINT   = OUTPUT_DIR / "extraction_checkpoint.json"
LOG_FILE     = OUTPUT_DIR / "extraction_log.txt"
SAM2_WEIGHTS = MODEL_DIR / "sam2.1_hiera_base_plus.pt"
SAM2_CONFIG  = "configs/sam2.1/sam2.1_hiera_b+.yaml"
PATCH_SIZE   = 224
MIN_MASK_PX  = 100
SEED         = 42


def parse_args():
    parser = argparse.ArgumentParser(
        description="Extract SAM2 point-prompt Option A coral patches for training."
    )
    parser.add_argument("--manifest", default=str(MANIFEST_CSV),
                        help="Split manifest CSV generated by src/data/build_manifest.py")
    parser.add_argument("--output-dir", default=str(OUTPUT_DIR),
                        help="Output folder for SAM2 patches")
    parser.add_argument("--sam2-weights", default=str(SAM2_WEIGHTS),
                        help="Path to SAM2 weights")
    parser.add_argument("--sam2-config", default=SAM2_CONFIG,
                        help="SAM2 config path/name, for example configs/sam2.1/sam2.1_hiera_b+.yaml")
    parser.add_argument("--sam2-repo", default=str(SAM2_REPO),
                        help="Optional local SAM2 repo path if sam2 is not installed")
    parser.add_argument("--patch-size", type=int, default=PATCH_SIZE,
                        help="Final saved patch size")
    parser.add_argument("--min-mask-px", type=int, default=MIN_MASK_PX,
                        help="Minimum mask area in pixels")
    return parser.parse_args()


def configure_from_args(args):
    global SAM2_REPO, OUTPUT_DIR, MANIFEST_CSV, CHECKPOINT, LOG_FILE
    global SAM2_WEIGHTS, SAM2_CONFIG, PATCH_SIZE, MIN_MASK_PX

    SAM2_REPO = resolve_path(args.sam2_repo)
    OUTPUT_DIR = resolve_path(args.output_dir)
    MANIFEST_CSV = resolve_path(args.manifest)
    CHECKPOINT = OUTPUT_DIR / "extraction_checkpoint.json"
    LOG_FILE = OUTPUT_DIR / "extraction_log.txt"
    SAM2_WEIGHTS = resolve_path(args.sam2_weights)
    SAM2_CONFIG = str(args.sam2_config)
    PATCH_SIZE = args.patch_size
    MIN_MASK_PX = args.min_mask_px

    if SAM2_REPO.exists() and str(SAM2_REPO) not in sys.path:
        sys.path.insert(0, str(SAM2_REPO))

    if not MANIFEST_CSV.exists():
        raise FileNotFoundError(
            f"Split manifest not found: {MANIFEST_CSV}\n"
            "Run python src/data/build_manifest.py first, or pass --manifest /path/to/split_manifest.csv."
        )
    if not SAM2_WEIGHTS.exists():
        raise FileNotFoundError(
            f"SAM2 weights not found: {SAM2_WEIGHTS}\n"
            "Download the externally hosted weights into models/sam2.1_hiera_base_plus.pt, "
            "or pass --sam2-weights /path/to/sam2.1_hiera_base_plus.pt."
        )


LABEL_MAP = {
    "MadMir":"Madracis_mirabilis","Madmira":"Madracis_mirabilis",
    "AgAga":"Agaricia_agaricites","BL_Aga":"Agaricia_agaricites",
    "AAGA":"Agaricia_agaricites","AAGA_BL":"Agaricia_agaricites","AGAAGA":"Agaricia_agaricites",
    "OrbAnn":"Orbicella_annularis","BL_OrbAnn":"Orbicella_annularis",
    "OANN":"Orbicella_annularis","OANN_BL":"Orbicella_annularis","ORBANN":"Orbicella_annularis",
    "Lobo":"Lobophyllia_spp","LOBO":"Lobophyllia_spp",
    "OrbFav":"Orbicella_faveolata","BL_OrbFav":"Orbicella_faveolata",
    "OFAV":"Orbicella_faveolata","OFAV_BL":"Orbicella_faveolata","ORBFAV":"Orbicella_faveolata",
    "MCav":"Montastraea_cavernosa","BL_MCav":"Montastraea_cavernosa",
    "MCAV":"Montastraea_cavernosa","MCAV_BL":"Montastraea_cavernosa",
    "PorAstr":"Porites_astreoides","BL_PAst":"Porites_astreoides",
    "PAST":"Porites_astreoides","PAST_BL":"Porites_astreoides",
    "Millepo":"Millepora_spp","Mil_spp":"Millepora_spp",
    "MILA":"Millepora_spp","MILC":"Millepora_spp","MILLE":"Millepora_spp","BL_Mille":"Millepora_spp",
    "SidSid":"Siderastrea_siderea","BL_SidSid":"Siderastrea_siderea",
    "SSID":"Siderastrea_siderea","SSID_BL":"Siderastrea_siderea",
    "ColNat":"Colpophyllia_natans","BL_CoNat":"Colpophyllia_natans",
    "CNAT":"Colpophyllia_natans","CNAT_BL":"Colpophyllia_natans","CNAt":"Colpophyllia_natans",
    "DipStr":"Pseudodiploria_strigosa","BL_DipStr":"Pseudodiploria_strigosa",
    "PSTRI":"Pseudodiploria_strigosa","PSTR_BL":"Pseudodiploria_strigosa",
    "MAUR":"Madracis_auretenra","MALC":"Madracis_auretenra","MLAM":"Madracis_auretenra",
    "StInt":"Stephanocoenia_intersepta","BL_StInt":"Stephanocoenia_intersepta",
    "SINT":"Stephanocoenia_intersepta","SINT_BL":"Stephanocoenia_intersepta",
    "OrbFrank":"Orbicella_franksi","BL_OrbFran":"Orbicella_franksi",
    "OFRA":"Orbicella_franksi","OFRA_BL":"Orbicella_franksi",
    "ATEN":"Acropora_tenuifolia","ATEN_BL":"Acropora_tenuifolia",
    "PorPor":"Porites_porites","BL_PorPor":"Porites_porites",
    "PPOR":"Porites_porites","PPOR_BL":"Porites_porites","POP":"Porites_porites",
    "MeanMean":"Meandrina_meandrites","BL_Mean":"Meandrina_meandrites",
    "MMEA":"Meandrina_meandrites","MMEA_BL":"Meandrina_meandrites","MM":"Meandrina_meandrites",
}

SPECIES_LIST   = sorted(set(LABEL_MAP.values()))
SPECIES_TO_IDX = {s: i for i, s in enumerate(SPECIES_LIST)}
random.seed(SEED); np.random.seed(SEED)
log = None


def setup_logging():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s  %(message)s",
        handlers=[
            logging.StreamHandler(),
            logging.FileHandler(LOG_FILE, mode="a"),
        ]
    )
    return logging.getLogger(__name__)


def load_annotations():
    log.info("Loading annotations ...")
    df = pd.read_csv(MANIFEST_CSV)
    # Species in manifest are already canonical names (not raw codes)
    # Just validate they are in our known species list
    df["species_mapped"] = df["species"].apply(
        lambda s: s if s in SPECIES_LIST else None)
    df = df[df["species_mapped"].notna()].copy()
    log.info(f"  {len(df):,} annotations across {df['img_path'].nunique():,} images")

    # Clean paths — manifest may have embedded newlines from CSV formatting
    df["img_path"] = df["img_path"].str.replace(r"\n", "", regex=False)\
                                   .str.replace("\n", "", regex=False)\
                                   .str.strip()

    # Clean embedded newlines and normalize path separators
    df["img_path"] = (df["img_path"]
                      .str.replace("\n", "", regex=False)
                      .str.replace("\\n", "", regex=False)
                      .str.strip()
)

    by_image = defaultdict(list)
    for _, row in df.iterrows():
        by_image[row["img_path"]].append({
            "row":      int(row["row"]),
            "col":      int(row["col"]),
            "species":  row["species_mapped"],
            "split":    row["split"],
            "img_name": row["img_name"],
        })

    log.info("  Per-species counts:")
    for sp, n in df["species_mapped"].value_counts().items():
        log.info(f"    {sp:<35} {n:>6}")
    return by_image


def load_sam2():
    from sam2.build_sam import build_sam2
    from sam2.sam2_image_predictor import SAM2ImagePredictor
    device = "cuda" if torch.cuda.is_available() else "cpu"
    log.info(f"Loading SAM2 on {device} ...")
    model     = build_sam2(SAM2_CONFIG, str(SAM2_WEIGHTS), device=device)
    predictor = SAM2ImagePredictor(model)
    log.info("SAM2 loaded.")
    return predictor, device


def get_sam2_mask(predictor, row, col):
    try:
        point_coords = np.array([[col, row]], dtype=np.float32)
        point_labels = np.array([1])
        with torch.inference_mode(), torch.autocast(
            "cuda" if torch.cuda.is_available() else "cpu",
            dtype=torch.bfloat16
        ):
            masks, scores, _ = predictor.predict(
                point_coords=point_coords,
                point_labels=point_labels,
                multimask_output=True,
            )
        # Prefer mask containing the annotation point
        best_mask = None; best_score = -1
        for mask, score in zip(masks, scores):
            r = min(max(0, row), mask.shape[0]-1)
            c = min(max(0, col), mask.shape[1]-1)
            if mask[r, c] and float(score) > best_score:
                best_mask = mask; best_score = float(score)
        if best_mask is None:
            best_mask = masks[int(np.argmax(scores))]
        return best_mask.astype(bool)
    except Exception:
        return None


def extract_patch(img_rgb, mask):
    if mask is None or mask.sum() < MIN_MASK_PX:
        return None
    h, w   = img_rgb.shape[:2]
    rows_m = np.any(mask, axis=1)
    cols_m = np.any(mask, axis=0)
    y1 = int(np.argmax(rows_m))
    y2 = int(len(rows_m) - np.argmax(rows_m[::-1]) - 1)
    x1 = int(np.argmax(cols_m))
    x2 = int(len(cols_m) - np.argmax(cols_m[::-1]) - 1)
    if y2 <= y1 or x2 <= x1:
        return None
    side   = max(y2-y1, x2-x1)
    pad    = max(4, int(side * 0.10))
    side_p = side + 2*pad
    cy = (y1+y2)//2; cx = (x1+x2)//2
    ny1 = max(0, cy-side_p//2); nx1 = max(0, cx-side_p//2)
    ny2 = min(h, ny1+side_p);   nx2 = min(w, nx1+side_p)
    crop = img_rgb[ny1:ny2, nx1:nx2].copy()
    crop[~mask[ny1:ny2, nx1:nx2]] = 0
    if crop.shape[0] == 0 or crop.shape[1] == 0:
        return None
    return cv2.resize(crop, (PATCH_SIZE, PATCH_SIZE),
                      interpolation=cv2.INTER_AREA)


def main():
    global log
    args = parse_args()
    configure_from_args(args)
    log = setup_logging()
    log.info("SAM2 Point-Prompt Patch Extractor")

    for split in ("train", "val", "test"):
        for sp in SPECIES_LIST:
            (OUTPUT_DIR / split / sp).mkdir(parents=True, exist_ok=True)

    by_image = load_annotations()

    completed_keys = set()
    if CHECKPOINT.exists():
        with open(CHECKPOINT) as f:
            completed_keys = set(json.load(f).get("completed", []))
        log.info(f"Resuming: {len(completed_keys):,} done")

    predictor, device = load_sam2()

    csv_path   = OUTPUT_DIR / "split_manifest.csv"
    csv_exists = csv_path.exists() and len(completed_keys) > 0
    csv_file   = open(csv_path, "a" if csv_exists else "w",
                      newline="", encoding="utf-8")
    fieldnames = ["img_path","img_name","species","label_idx",
                  "split","patch_path","row","col","mask_area"]
    writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
    if not csv_exists:
        writer.writeheader()

    n_saved = n_no_mask = n_error = n_skipped = 0
    species_counts = defaultdict(int)
    t_start = time.time()
    img_paths = list(by_image.keys())
    log.info(f"Processing {len(img_paths):,} images ...")

    for img_idx, img_path in enumerate(img_paths):
        annotations = by_image[img_path]
        all_keys    = [f"{img_path}_{a['row']}_{a['col']}" for a in annotations]

        if all(k in completed_keys for k in all_keys):
            n_skipped += len(annotations)
            continue

        # cv2.imread can't handle backslashes in Linux paths
        # Use numpy frombuffer as workaround
        try:
            with open(img_path, "rb") as f:
                img_buf = np.frombuffer(f.read(), dtype=np.uint8)
            img_bgr = cv2.imdecode(img_buf, cv2.IMREAD_COLOR)
        except Exception:
            img_bgr = None
        if img_bgr is None:
            n_error += len(annotations)
            for k in all_keys: completed_keys.add(k)
            continue

        img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)

        try:
            with torch.inference_mode(), torch.autocast(
                device, dtype=torch.bfloat16
            ):
                predictor.set_image(img_rgb)
        except Exception as e:
            log.warning(f"  Encode failed {Path(img_path).name}: {e}")
            n_error += len(annotations)
            for k in all_keys: completed_keys.add(k)
            continue

        for ann in annotations:
            key = f"{img_path}_{ann['row']}_{ann['col']}"
            if key in completed_keys:
                continue

            mask  = get_sam2_mask(predictor, ann["row"], ann["col"])
            patch = extract_patch(img_rgb, mask)

            if patch is None:
                n_no_mask += 1
                completed_keys.add(key)
                continue

            sp_safe    = ann["species"]
            fname      = f"{Path(img_path).stem}_r{ann['row']}_c{ann['col']}.jpg"
            patch_path = OUTPUT_DIR / ann["split"] / sp_safe / fname
            cv2.imwrite(str(patch_path),
                        cv2.cvtColor(patch, cv2.COLOR_RGB2BGR),
                        [cv2.IMWRITE_JPEG_QUALITY, 92])
            writer.writerow({
                "img_path":  img_path,
                "img_name":  ann["img_name"],
                "species":   sp_safe,
                "label_idx": SPECIES_TO_IDX[sp_safe],
                "split":     ann["split"],
                "patch_path":str(patch_path),
                "row":       ann["row"],
                "col":       ann["col"],
                "mask_area": int(mask.sum()) if mask is not None else 0,
            })
            n_saved += 1
            species_counts[sp_safe] += 1
            completed_keys.add(key)

        if (img_idx+1) % 50 == 0:
            elapsed   = time.time() - t_start
            rate      = (img_idx+1) / max(elapsed, 1)
            remaining = (len(img_paths)-img_idx-1) / max(rate, 0.001)
            log.info(f"  [{img_idx+1:5d}/{len(img_paths)}]  "
                     f"saved={n_saved:,}  no_mask={n_no_mask}  "
                     f"errors={n_error}  ETA={remaining/3600:.1f}h")
            with open(CHECKPOINT, "w") as f:
                json.dump({"completed": list(completed_keys)}, f)
            csv_file.flush()

    csv_file.close()
    with open(CHECKPOINT, "w") as f:
        json.dump({"completed": list(completed_keys)}, f)
    with open(OUTPUT_DIR / "label_map.json", "w") as f:
        json.dump(SPECIES_TO_IDX, f, indent=2)

    elapsed = time.time() - t_start
    log.info(f"\n{'='*60}")
    log.info(f"Patches saved : {n_saved:,}")
    log.info(f"No mask       : {n_no_mask:,}")
    log.info(f"Errors        : {n_error:,}")
    log.info(f"Time          : {elapsed/3600:.1f}h")
    log.info(f"\nPer species:")
    for sp, n in sorted(species_counts.items(), key=lambda x: -x[1]):
        log.info(f"  {sp:<35} {n:>6}")
    log.info(f"\nNext: python train.py --dataset sam2")


if __name__ == "__main__":
    main()

