"""
Prepare CoralSCOP Training Data
=================================
Generates CoralSCOP training data using point prompts.

For each CoralNet annotation point (row, col, species):
    Feed the point as a foreground prompt directly to CoralSCOP
    CoralSCOP generates a mask for the coral colony at that point
    Label = species from the annotation

This produces one labelled mask per annotation point (~46,000 total)
with guaranteed coral content — far better than automatic mode which
segments everything and rarely captures annotated colonies.

Output:
    outputs/coralscop_training_data/
        training_samples.csv     one row per labelled mask
        label_stats.txt          how many samples per species

Usage from the repository root:
    conda activate coralnet10
    python src/patches/extract_coralscop.py

Default local paths:
    outputs/split_manifest.csv          manifest from src/data/build_manifest.py
    models/vit_b_coralscop.pth          CoralSCOP weights, externally downloaded
    external/CoralSCOP/                 optional local CoralSCOP repo clone

All defaults can be overridden with command-line arguments.

This takes ~2-3 hours for 12,859 images. It only needs to run once.
The output CSV is then used by finetune_coralscop_v2.py for training.
"""

import argparse
import csv
import json
import sys
import time
from collections import Counter, defaultdict
from pathlib import Path

import cv2
import numpy as np
import pandas as pd
import torch


# ── Project paths ─────────────────────────────────────────────────────────────

def find_project_root(script_path: Path) -> Path:
    """Return the repository root so the script works from any current folder."""
    for parent in [script_path.parent, *script_path.parents]:
        if (parent / "README.md").exists() or (parent / ".git").exists():
            return parent

    # Expected GitHub location: src/patches/<this_file>.py
    if script_path.parent.name == "patches" and script_path.parent.parent.name == "src":
        return script_path.parent.parent.parent

    return script_path.parent


PROJECT_ROOT = find_project_root(Path(__file__).resolve())
MODEL_DIR = PROJECT_ROOT / "models"
OUTPUT_ROOT = PROJECT_ROOT / "outputs"


def repo_path(*parts: str) -> Path:
    """Build an absolute path inside this repository."""
    return PROJECT_ROOT.joinpath(*parts)


def resolve_path(path_value) -> Path:
    """Resolve user paths. Relative paths are interpreted from the repo root."""
    path = Path(path_value).expanduser()
    if path.is_absolute():
        return path
    return repo_path(str(path)).resolve()

# ── Configuration ─────────────────────────────────────────────────────────────

CORALSCOP_DIR = repo_path("external", "CoralSCOP")
DATA_ROOT     = repo_path("data", "CoralNet_Data")
OUTPUT_DIR    = repo_path("outputs", "coralscop_training_data")
WEIGHTS_PATH  = MODEL_DIR / "vit_b_coralscop.pth"
MANIFEST_CSV  = repo_path("outputs", "split_manifest.csv")
CHECKPOINT    = OUTPUT_DIR / "progress_checkpoint.json"


def parse_args():
    parser = argparse.ArgumentParser(
        description="Generate CoralSCOP point-prompt training data from CoralNet annotations."
    )
    parser.add_argument("--manifest", default=str(MANIFEST_CSV),
                        help="Split manifest CSV generated by src/data/build_manifest.py")
    parser.add_argument("--output-dir", default=str(OUTPUT_DIR),
                        help="Output folder for CoralSCOP training samples")
    parser.add_argument("--weights", default=str(WEIGHTS_PATH),
                        help="Path to vit_b_coralscop.pth")
    parser.add_argument("--coralscop-repo", default=str(CORALSCOP_DIR),
                        help="Optional local CoralSCOP repo path if segment_anything is not installed")
    return parser.parse_args()


def configure_from_args(args):
    global CORALSCOP_DIR, OUTPUT_DIR, WEIGHTS_PATH, MANIFEST_CSV, CHECKPOINT

    CORALSCOP_DIR = resolve_path(args.coralscop_repo)
    OUTPUT_DIR = resolve_path(args.output_dir)
    WEIGHTS_PATH = resolve_path(args.weights)
    MANIFEST_CSV = resolve_path(args.manifest)
    CHECKPOINT = OUTPUT_DIR / "progress_checkpoint.json"

    if CORALSCOP_DIR.exists() and str(CORALSCOP_DIR) not in sys.path:
        sys.path.insert(0, str(CORALSCOP_DIR))

    if not MANIFEST_CSV.exists():
        raise FileNotFoundError(
            f"Split manifest not found: {MANIFEST_CSV}\n"
            "Run python src/data/build_manifest.py first, or pass --manifest /path/to/split_manifest.csv."
        )
    if not WEIGHTS_PATH.exists():
        raise FileNotFoundError(
            f"CoralSCOP weights not found: {WEIGHTS_PATH}\n"
            "Download the externally hosted weights into models/vit_b_coralscop.pth, "
            "or pass --weights /path/to/vit_b_coralscop.pth."
        )


SAM_IMG_SIZE = 1024
MIN_AREA_FRAC = 0.002   # ignore masks smaller than 0.2% of image
MIN_POINTS_IN_MASK = 1  # minimum annotation points needed to label a mask

LABEL_MAP = {
    "MadMir":"Madracis_mirabilis",
    "AgAga":"Agaricia_agaricites","BL_Aga":"Agaricia_agaricites",
    "AAGA":"Agaricia_agaricites","AAGA_BL":"Agaricia_agaricites","AGAAGA":"Agaricia_agaricites",
    "OrbAnn":"Orbicella_annularis","BL_OrbAnn":"Orbicella_annularis",
    "OANN":"Orbicella_annularis","OANN_BL":"Orbicella_annularis","ORBANN":"Orbicella_annularis",
    "Lobo":"Lobophyllia_spp","LOBO":"Lobophyllia_spp",
    "OrbFav":"Orbicella_faveolata","BL_OrbFav":"Orbicella_faveolata",
    "OFAV":"Orbicella_faveolata","OFAV_BL":"Orbicella_faveolata","ORBFAV":"Orbicella_faveolata",
    "MCav":"Montastraea_cavernosa","BL_MCav":"Montastraea_cavernosa",
    "MCAV":"Montastraea_cavernosa","MCAV_BL":"Montastraea_cavernosa",
    "PorAstr":"Porites_astreoides","BL_PAst":"Porites_astreoides",
    "PAST":"Porites_astreoides","PAST_BL":"Porites_astreoides",
    "Millepo":"Millepora_spp","Mil_spp":"Millepora_spp",
    "MILA":"Millepora_spp","MILC":"Millepora_spp","MILLE":"Millepora_spp","BL_Mille":"Millepora_spp",
    "SidSid":"Siderastrea_siderea","BL_SidSid":"Siderastrea_siderea",
    "SSID":"Siderastrea_siderea","SSID_BL":"Siderastrea_siderea",
    "ColNat":"Colpophyllia_natans","BL_CoNat":"Colpophyllia_natans",
    "CNAT":"Colpophyllia_natans","CNAT_BL":"Colpophyllia_natans","CNAt":"Colpophyllia_natans",
    "DipStr":"Pseudodiploria_strigosa","BL_DipStr":"Pseudodiploria_strigosa",
    "PSTRI":"Pseudodiploria_strigosa","PSTR_BL":"Pseudodiploria_strigosa",
    "MAUR":"Madracis_auretenra","MALC":"Madracis_auretenra","MLAM":"Madracis_auretenra",
    "StInt":"Stephanocoenia_intersepta","BL_StInt":"Stephanocoenia_intersepta",
    "SINT":"Stephanocoenia_intersepta","SINT_BL":"Stephanocoenia_intersepta",
    "OrbFrank":"Orbicella_franksi","BL_OrbFran":"Orbicella_franksi",
    "OFRA":"Orbicella_franksi","OFRA_BL":"Orbicella_franksi",
    "ATEN":"Acropora_tenuifolia","ATEN_BL":"Acropora_tenuifolia",
    "PorPor":"Porites_porites","BL_PorPor":"Porites_porites",
    "PPOR":"Porites_porites","PPOR_BL":"Porites_porites","POP":"Porites_porites",
    "MeanMean":"Meandrina_meandrites","BL_Mean":"Meandrina_meandrites",
    "MMEA":"Meandrina_meandrites","MMEA_BL":"Meandrina_meandrites","MM":"Meandrina_meandrites",
}

SPECIES_LIST  = sorted(set(LABEL_MAP.values()))
SPECIES_TO_IDX = {s: i+1 for i, s in enumerate(SPECIES_LIST)}  # 1-indexed, 0=background


def load_annotations():
    """
    Load all CoralNet annotations and group by image path.
    Returns dict: img_path_str -> list of (row, col, species) tuples
    """
    print("Loading annotations ...")
    manifest = pd.read_csv(MANIFEST_CSV)

    # Only use train split for generating training data
    train = manifest[manifest["split"] == "train"]
    print(f"  Train annotations: {len(train):,}")

    # Group by image path
    by_image = defaultdict(list)
    for _, row in train.iterrows():
        species = row["species"]
        if species not in SPECIES_TO_IDX:
            continue
        by_image[row["img_path"]].append((
            int(row["row"]),
            int(row["col"]),
            species,
        ))

    print(f"  Unique training images: {len(by_image):,}")
    return by_image


def point_in_mask(mask, row, col):
    """Check if annotation point (row=y, col=x) falls inside a boolean mask."""
    h, w = mask.shape
    r = min(max(0, row), h-1)
    c = min(max(0, col), w-1)
    return bool(mask[r, c])


def mask_centroid(mask):
    """Return (row, col) centroid of a boolean mask."""
    rows, cols = np.where(mask)
    if len(rows) == 0:
        return None
    return float(np.mean(rows)), float(np.mean(cols))


def label_masks_from_points(masks, annotations, img_h, img_w):
    """
    Assign species labels to detected masks using two strategies:

    Strategy 1 (preferred): Point-in-mask
        Find all annotation points that fall inside the mask.
        If >= 1 point found and 70%+ agree on species -> label the mask.

    Strategy 2 (fallback): Nearest-point
        If no points fall inside the mask, find the nearest annotation
        point to the mask centroid. If it is within MAX_DIST_FRAC of the
        image diagonal, assign that species (with lower confidence flag).

    This dramatically increases labelled mask yield for images with sparse
    annotation points that don't happen to land inside SAM-detected masks.
    """
    MAX_DIST_FRAC = 0.08   # nearest point must be within 8% of image diagonal
    img_diag = np.sqrt(img_h**2 + img_w**2)
    max_dist = img_diag * MAX_DIST_FRAC

    labelled = []

    for mask_data in masks:
        seg = mask_data["segmentation"]
        if seg.shape != (img_h, img_w):
            seg = cv2.resize(seg.astype(np.uint8), (img_w, img_h),
                             interpolation=cv2.INTER_NEAREST).astype(bool)

        # Strategy 1: points inside mask
        points_inside = []
        for (row, col, species) in annotations:
            if point_in_mask(seg, row, col):
                points_inside.append(species)

        if points_inside:
            species_counts  = Counter(points_inside)
            majority_sp, majority_n = species_counts.most_common(1)[0]
            agreement = majority_n / len(points_inside)
            if agreement < 0.70:
                continue   # ambiguous mask, skip
            method = "inside"
            n_points = len(points_inside)
        else:
            # Strategy 2: nearest point to mask centroid
            centroid = mask_centroid(seg)
            if centroid is None:
                continue
            cr, cc = centroid
            best_dist = float("inf")
            best_sp   = None
            for (row, col, species) in annotations:
                dist = np.sqrt((row - cr)**2 + (col - cc)**2)
                if dist < best_dist:
                    best_dist = dist
                    best_sp   = species
            if best_dist > max_dist or best_sp is None:
                continue   # no nearby annotation point
            majority_sp = best_sp
            agreement   = round(1.0 - best_dist / max_dist, 3)  # distance-based confidence
            method      = "nearest"
            n_points    = 1

        label_idx = SPECIES_TO_IDX.get(majority_sp)
        if label_idx is None:
            continue

        x, y, bw, bh = mask_data["bbox"]
        labelled.append({
            "species":      majority_sp,
            "label_idx":    label_idx,
            "n_points":     n_points,
            "agreement":    round(agreement, 3),
            "method":       method,
            "bbox_x1":      int(x),
            "bbox_y1":      int(y),
            "bbox_x2":      int(x + bw),
            "bbox_y2":      int(y + bh),
            "area":         mask_data["area"],
            "area_frac":    round(mask_data["area"] / (img_h * img_w), 4),
            "stability":    round(float(mask_data.get("stability_score", 0)), 3),
            "iou":          round(float(mask_data.get("predicted_iou", 0)), 3),
        })

    return labelled


def main():
    args = parse_args()
    configure_from_args(args)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"Device: {device}")

    # Load annotations grouped by image
    by_image = load_annotations()

    # Load CoralSCOP
    from segment_anything import build_sam_vit_b, SamAutomaticMaskGenerator
    print(f"\nLoading CoralSCOP from {WEIGHTS_PATH} ...")
    sam   = build_sam_vit_b(checkpoint=str(WEIGHTS_PATH))
    sam.to(device)
    sam.eval()
    print("CoralSCOP loaded.")

    # Load resume checkpoint
    completed = set()
    if CHECKPOINT.exists():
        with open(CHECKPOINT) as f:
            completed = set(json.load(f).get("completed", []))
        print(f"Resuming: {len(completed):,} images already processed")

    # Output CSV
    csv_path    = OUTPUT_DIR / "training_samples.csv"
    csv_exists  = csv_path.exists() and len(completed) > 0
    csv_file    = open(csv_path, "a" if csv_exists else "w", newline="",
                       encoding="utf-8")
    fieldnames  = ["img_path", "species", "label_idx", "n_points",
                   "agreement", "method", "bbox_x1", "bbox_y1", "bbox_x2", "bbox_y2",
                   "area", "area_frac", "stability", "iou", "split"]
    writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
    if not csv_exists:
        writer.writeheader()

    # Build flat list of all annotation points (one entry per point)
    all_points = []
    for img_path, anns in by_image.items():
        for (row, col, species) in anns:
            all_points.append((img_path, row, col, species))

    # Filter already completed points using img+row+col key
    completed_keys = set()
    if CHECKPOINT.exists():
        with open(CHECKPOINT) as f:
            completed_keys = set(json.load(f).get("completed", []))

    remaining = [(p, r, c, s) for p, r, c, s in all_points
                 if f"{p}_{r}_{c}" not in completed_keys]

    total          = len(remaining)
    n_saved        = 0
    n_no_mask      = 0
    n_error        = 0
    species_counts = defaultdict(int)

    print(f"\nProcessing {total:,} annotation points using point prompts ...")
    print(f"(Saving labelled mask samples to {csv_path})\n")

    # Use SamPredictor (point prompt mode) instead of automatic generator
    from segment_anything import SamPredictor
    predictor = SamPredictor(sam)

    # Cache image embeddings — same image often has multiple annotation points
    current_img_path = None
    current_img_h    = None
    current_img_w    = None

    for i, (img_path, ann_row, ann_col, species) in enumerate(remaining):
        point_key = f"{img_path}_{ann_row}_{ann_col}"

        # Load and encode image (only when image changes)
        if img_path != current_img_path:
            img_bgr = cv2.imread(img_path)
            if img_bgr is None:
                n_error += 1
                completed_keys.add(point_key)
                continue

            img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
            current_img_h, current_img_w = img_rgb.shape[:2]
            current_img_path = img_path

            try:
                predictor.set_image(img_rgb)
            except Exception as e:
                print(f"  Encode error {Path(img_path).name}: {e}")
                n_error += 1
                completed_keys.add(point_key)
                continue

        # Scale annotation point to image coordinates
        # (CoralNet row/col are pixel coordinates in original image)
        point_coords = np.array([[ann_col, ann_row]], dtype=np.float32)
        point_labels = np.array([1])   # 1 = foreground

        try:
            masks, scores, _ = predictor.predict(
                point_coords=point_coords,
                point_labels=point_labels,
                num_multimask_outputs=3,
            )
            # Pick highest-confidence mask
            best_idx  = int(np.argmax(scores))
            mask_bool = masks[best_idx].astype(bool)
            score     = float(scores[best_idx])
        except Exception as e:
            n_no_mask += 1
            completed_keys.add(point_key)
            continue

        # Filter too-small masks
        img_area  = current_img_h * current_img_w
        mask_area = int(np.sum(mask_bool))
        area_frac = mask_area / img_area
        if area_frac < MIN_AREA_FRAC:
            n_no_mask += 1
            completed_keys.add(point_key)
            continue

        # Compute bounding box from mask
        rows_m = np.any(mask_bool, axis=1)
        cols_m = np.any(mask_bool, axis=0)
        y1 = int(np.argmax(rows_m))
        y2 = int(len(rows_m) - np.argmax(rows_m[::-1]) - 1)
        x1 = int(np.argmax(cols_m))
        x2 = int(len(cols_m) - np.argmax(cols_m[::-1]) - 1)

        label_idx = SPECIES_TO_IDX.get(species)
        if label_idx is None:
            completed_keys.add(point_key)
            continue

        writer.writerow({
            "img_path":  img_path,
            "species":   species,
            "label_idx": label_idx,
            "n_points":  1,
            "agreement": round(score, 3),
            "method":    "point_prompt",
            "bbox_x1":   x1,
            "bbox_y1":   y1,
            "bbox_x2":   x2,
            "bbox_y2":   y2,
            "area":      mask_area,
            "area_frac": round(area_frac, 4),
            "stability": round(score, 3),
            "iou":       round(score, 3),
            "split":     "train",
        })
        species_counts[species] += 1
        n_saved += 1
        completed_keys.add(point_key)

        # Progress every 500 points
        if (i + 1) % 500 == 0 or i == total - 1:
            print(f"  [{i+1:5d}/{total}]  "
                  f"saved={n_saved:,}  "
                  f"no_mask={n_no_mask}  "
                  f"errors={n_error}")
            with open(CHECKPOINT, "w") as f:
                json.dump({"completed": list(completed_keys)}, f)
            csv_file.flush()

    csv_file.close()

    # Save checkpoint
    with open(CHECKPOINT, "w") as f:
        json.dump({"completed": list(completed_keys)}, f)

    # Print summary
    print(f"\n{'='*60}")
    print(f"Total labelled masks saved : {n_saved:,}")
    print(f"Images with no masks       : {n_no_mask}")
    print(f"Images with errors         : {n_error}")
    print(f"\nSamples per species:")
    for sp, n in sorted(species_counts.items(), key=lambda x: -x[1]):
        print(f"  {sp:<35} {n:>6}")

    # Save stats
    stats_path = OUTPUT_DIR / "label_stats.txt"
    with open(stats_path, "w") as f:
        f.write(f"Total labelled masks: {n_saved:,}\n\n")
        f.write("Samples per species:\n")
        for sp, n in sorted(species_counts.items(), key=lambda x: -x[1]):
            f.write(f"  {sp:<35} {n}\n")
    print(f"\nStats saved to: {stats_path}")
    print(f"Training data saved to: {csv_path}")
    print(f"\nNext step: run finetune_coralscop_v2.py")


if __name__ == "__main__":
    main()
